/**
 * Projects US state outlines into SVG path data for the banner generator.
 *
 *   node scripts/build-us-map.mjs
 *
 * Source: the public-domain us-states GeoJSON (cached under scripts/.cache).
 * Output: scripts/lib/us-map.generated.json
 *   { viewBox, states: { "Ohio": { d, cx, cy, area } }, hawaii: {...} }
 *
 * Albers conic equal-area for the lower 48 — the projection every US press map
 * uses, so state shapes read as familiar rather than stretched. Hawaii is
 * projected on its own so it can be drawn as its own inset.
 */
import fs from 'node:fs/promises'
import path from 'node:path'

const SRC = path.join(import.meta.dirname, '.cache', 'us-states.geojson')
const OUT = path.join(import.meta.dirname, 'lib', 'us-map.generated.json')

/** Albers conic equal-area. Returns unscaled planar coords. */
function makeAlbers(lat0, lon0, phi1, phi2) {
  const rad = (d) => (d * Math.PI) / 180
  const s1 = Math.sin(rad(phi1))
  const s2 = Math.sin(rad(phi2))
  const n = (s1 + s2) / 2
  const C = Math.cos(rad(phi1)) ** 2 + 2 * n * s1
  const rho = (phi) => Math.sqrt(C - 2 * n * Math.sin(rad(phi))) / n
  const rho0 = rho(lat0)
  return ([lon, lat]) => {
    const theta = n * rad(lon - lon0)
    const r = rho(lat)
    // Negated: the projection puts north at +y, SVG puts it at -y.
    return [r * Math.sin(theta), r * Math.cos(theta) - rho0]
  }
}

const ringsOf = (geom) =>
  geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates

/** Drops points closer than `tol` in projected space — keeps the files small. */
function simplify(points, tol) {
  const out = [points[0]]
  for (const p of points.slice(1)) {
    const last = out[out.length - 1]
    if (Math.hypot(p[0] - last[0], p[1] - last[1]) >= tol) out.push(p)
  }
  return out.length >= 4 ? out : points
}

const ringArea = (pts) => {
  let a = 0
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) {
    a += pts[j][0] * pts[i][1] - pts[i][0] * pts[j][1]
  }
  return Math.abs(a / 2)
}

function buildGroup(features, project, box, minAreaRatio) {
  // First pass: project everything to find the bounding box.
  const shapes = features.map((f) => ({
    name: f.properties.name,
    polys: ringsOf(f.geometry).map((poly) => poly.map((ring) => ring.map(project))),
  }))

  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity
  for (const s of shapes) {
    for (const poly of s.polys) {
      for (const [x, y] of poly[0]) {
        if (x < minX) minX = x
        if (x > maxX) maxX = x
        if (y < minY) minY = y
        if (y > maxY) maxY = y
      }
    }
  }

  const scale = Math.min(box.w / (maxX - minX), box.h / (maxY - minY))
  const offX = box.x + (box.w - (maxX - minX) * scale) / 2
  const offY = box.y + (box.h - (maxY - minY) * scale) / 2
  const to = ([x, y]) => [(x - minX) * scale + offX, (y - minY) * scale + offY]
  const r2 = (n) => Math.round(n * 10) / 10

  const states = {}
  for (const s of shapes) {
    // Screen-space areas, so islands can be dropped by visual size.
    const rings = s.polys.map((poly) => poly[0].map(to))
    const areas = rings.map(ringArea)
    const biggest = Math.max(...areas)
    const kept = rings.filter((_, i) => areas[i] >= biggest * minAreaRatio)

    const d = kept
      .map((ring) => {
        const pts = simplify(ring, 0.7)
        return `M${pts.map(([x, y]) => `${r2(x)},${r2(y)}`).join('L')}Z`
      })
      .join('')

    // Centroid of the largest ring, for pin placement.
    const main = kept[areas.indexOf(biggest)] ?? kept[0]
    let cx = 0, cy = 0
    for (const [x, y] of main) {
      cx += x
      cy += y
    }
    states[s.name] = {
      d,
      cx: r2(cx / main.length),
      cy: r2(cy / main.length),
      area: Math.round(biggest),
    }
  }
  return states
}

async function main() {
  const geo = JSON.parse(await fs.readFile(SRC, 'utf8'))
  const byName = (n) => geo.features.filter((f) => f.properties.name === n)
  const skip = new Set(['Alaska', 'Hawaii', 'Puerto Rico'])
  const lower48 = geo.features.filter((f) => !skip.has(f.properties.name))

  const albers = makeAlbers(37.5, -96, 29.5, 45.5)
  const states = buildGroup(lower48, albers, { x: 0, y: 0, w: 1000, h: 620 }, 0.05)

  // Hawaii gets its own projection; in a national frame it is a speck.
  const hawaii = buildGroup(byName('Hawaii'), makeAlbers(20.5, -157, 19, 22), { x: 0, y: 0, w: 1000, h: 500 }, 0.02)

  const out = {
    note: 'Generated by scripts/build-us-map.mjs — do not edit by hand.',
    viewBox: '0 0 1000 620',
    hawaiiViewBox: '0 0 1000 500',
    states,
    hawaii: hawaii.Hawaii,
  }
  await fs.writeFile(OUT, JSON.stringify(out))
  const kb = (JSON.stringify(out).length / 1024).toFixed(0)
  console.log(`${Object.keys(states).length} states + Hawaii → scripts/lib/us-map.generated.json (${kb}kb)`)
  for (const n of ['Ohio', 'Utah', 'Texas', 'California', 'Kansas', 'Georgia', 'North Carolina']) {
    const s = states[n]
    console.log(`  ${n.padEnd(15)} centroid ${s.cx},${s.cy}  path ${s.d.length} chars`)
  }
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
